version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER:  test
      POSTGRES_DB: test_db
    volumes:
      - './pkg/schema.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - "5432:5432"