openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'localhost:8081'
paths:
  "/health":
    get:
      description: Returns status 200
      responses:
        "200":
          description: server health responses
        "405":
          description: Method Not Allowed
          content:
            'application/json': { }